name: Test

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: node testnet.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update stats
          file_pattern: ./*.json
